### ISSUE TITLE
Doesn't work with "The Midnight" mod

### ISSUE THREAD

**Issue by jounihh** [Sunekaer/Simple-Discord-Rich-Presence#1]
https://github.com/Cryptic-Mushroom/The-Midnight/issues/280

**Comment by gegy1000** [comment]
I believe the lookup here is what is causing the issue:
https://github.com/Sunekaer/Simple-Discord-Rich-Presence/blob/9c977e3c02a5f33866d578154d63c78e5caf2b82/src/main/java/com/sunekaer/mods/sdrp/discord/DiscordRichPresence.java#L61
If the dimension type isn't in the map, it'll call setState with a null value causing the NPE

**Comment by Sunekaer** [comment]
I can load midnight and sdrp together just fine

**Comment by Sunekaer** [comment]
logs of this not working? please use some paste bin site

**Comment by gegy1000** [comment]
See the referenced issue's `latest.log`. I think it works fine in an isolated context but with more mods it breaks things

**Comment by Sunekaer** [comment]
Please paste it via https://paste.feed-the-beast.com, I have a policy of not downloading files I don't trust

**Comment by Sunekaer** [comment]
fix uploaded to curseforge
