### ISSUE TITLE
[Suggestion] Let us assign our own images

### ISSUE THREAD

**Issue by TheInfamousAlk** [Sunekaer/Simple-Discord-Rich-Presence#2]
It would be neat if the images could just be in a folder somewhere and we could replace them with images of the same name to be shown in rich presence. 

Also the "pack logo" is just this mod's logo? Shouldn't it be something minecraft related like a grass block or something?

**Comment by Sunekaer** [comment]
You set your images via the discord application that you make?

**Comment by Sunekaer** [comment]
![image](https://s1.sunekaer.com/i/10-10-2019_18-36-44_chrome.png)
![image](https://s1.sunekaer.com/i/10-10-2019_18-36-58_chrome.png)

**Comment by TheInfamousAlk** [comment]
I didn't know this existed. I just installed the mod and that's it. It would be nice if there was some sort of explanation on how to do this on the curseforge page. I assumed "rich presence application" was referring to applications other than discord.
