### ISSUE TITLE
Doesn't do anything.

### ISSUE THREAD

**Issue by KenaiTheWolf** [Sunekaer/Simple-Discord-Rich-Presence#5]
This mod literally does nothing after it loads. There's no rich presence after the mod is registered, nothing.

**Comment by Sunekaer** [comment]
Whats your config, do you have Game Activity enabled in discord, log file?

**Comment by DTRW919** [comment]
Same thing for me, I do have Game activity turned ON though

**Comment by Sunekaer** [comment]
Again, config and log file

**Comment by KenaiTheWolf** [comment]
Where would this log file be? Also I do have these things enabled.

**Comment by DTRW919** [comment]
Very confused am I, may you please do a step by step thing on how to do it please? The Curse Forge page just tells you to download it, not HOW it works

**Comment by KenaiTheWolf** [comment]
Please specify what logs you would like to be sent. Do you want the Latest.log, from Minecraft, or does your mod create its own log file.

Be specific, because your mod does not function when loaded on MacOS, it just loads and then never does anything else. I haven’t configured your mod away from the default state - again, absolutely nothing happens. There is ***no*** config file.

You developed this mod, we don’t know how it works, your documentation is poor, and I shouldn’t have to dig through your code to find the problem myself.

**Comment by DTRW919** [comment]
Kenai Is correct, I, and probably a THOUSAND+ people have been searching EVERYWHERE for a proper solution for rich presence integration for Minecraft. When we found this mod, we thought that it might work, so we hung on to this just to find that we did not know a SINGLE thing about how to operate this mod. So we counted on you, the owner of this mod to help us out, and I'm surprised that many other people have yet to ask about this. As the Lead-Developer of this mod, you should at least add a better description to your mod-page. Not just ASSUME that we will magically know how to work this through. I am dissapointed.

**Comment by Naxanria** [comment]
Log file: would be just the Minecraft log file. Mods don't usually make their own log files, it is added to the overall log.
Config: The config for the mod is indeed created by the mod. 
With these the Lead-Developer can check if and what might be wrong. Without it is shouting in the wind that wont get anywhere :)

**Comment by DTRW919** [comment]
well, all right then
